name: Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v3

    - uses: microsoft/setup-msbuild@v1

    - uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build the application
      run: msbuild /nologo /verbosity:n /t:Build

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: PxWeb
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3850D38E03784DBD806CCB5195A8FBD6 }}
        package: ./PxWeb/

