# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - PxWeb(Production), Build and deploy ASP .NET app

on: push

jobs:
  build-and-deploy:

    runs-on: windows-2019




    steps:

    - uses: actions/checkout@master

    - uses: microsoft/setup-msbuild@v1.0.2

    - uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore

    - name: Publish to folder
      #run: msbuild /nologo /verbosity:n /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"
      #run: msbuild /p:Configuration=Release PXWeb/PXWeb.csproj /p:DeployOnBuild=true /p:PublishProfile=filesystem.pubxml
      run: msbuild /nologo /verbosity:n /t:Build

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: PxWeb
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3850D38E03784DBD806CCB5195A8FBD6 }}
        package: ./PxWeb/

