name: .NET 4.x build

on: [push, pull_request]

jobs:

  build:

    #strategy:
    #  matrix:
    #    configuration: [Debug, Release]
    #    dotnet: [ '4.8' ]


    runs-on: windows-2019

    env:
      Solution_Name: PXWeb/PXWeb.csproj                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    ## Install the .NET workload
    #- name: Install .NET
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: ${{ matrix.dotnet }}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet Packages
      run: nuget restore PCAxis.PX-Web.sln

    - name: Restore the application
      #run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      run: msbuild /p:Configuration=Release PXWeb/PXWeb.csproj /p:DeployOnBuild=true /p:PublishProfile=filesystem.pubxml

      #env:
      #  Configuration: ${{ matrix.configuration }}


